# Generated by Django 5.0.4 on 2025-05-07 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeName', models.CharField(max_length=100)),
                ('employeeEmail', models.EmailField(max_length=254, unique=True)),
                ('employeeDepartment', models.CharField(max_length=100)),
            ],
        ),
    ]
