# Generated by Django 5.0.4 on 2025-05-08 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empapp', '0004_alter_employee_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(default='photos/default.jpeg', max_length=1000, upload_to='photos/'),
        ),
    ]
